# Generated by Django 5.0.8 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - must be unique', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether the product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the product was last updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['sku'],
                'indexes': [models.Index(fields=['sku'], name='idx_product_sku'), models.Index(fields=['active'], name='idx_product_active'), models.Index(fields=['sku', 'active'], name='idx_product_sku_active')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Webhook endpoint URL', max_length=500)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated')], help_text='Event type that triggers this webhook', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the webhook is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the webhook was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the webhook was last updated')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['event_type', 'url'],
                'indexes': [models.Index(fields=['event_type'], name='idx_webhook_event_type'), models.Index(fields=['is_active'], name='idx_webhook_is_active'), models.Index(fields=['event_type', 'is_active'], name='idx_webhook_event_active')],
                'unique_together': {('url', 'event_type')},
            },
        ),
    ]
