# Generated by Django 5.0.8 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("product.created", "Product Created"),
                    ("product.updated", "Product Updated"),
                    ("product.deleted", "Product Deleted"),
                    ("bulk_import.completed", "Bulk Import Completed"),
                ],
                help_text="Event type that triggers this webhook",
                max_length=50,
            ),
        ),
    ]
